### ISSUE TITLE
Second setThreadOptions call segfaults

### ISSUE THREAD

**Issue by Enchufa2** [RcppCore/RcppParallel#110]
It works fine on Fedora 31, but I get a segfault on Fedora 32+, and the main difference is gcc10.

```
$ docker run --rm -it fedora:rawhide
# dnf install R -y
# R -e 'install.packages("RcppParallel", repos="https://cran.r-project.org")'
# R -d valgrind --vanilla -e 'for (i in 1:2) RcppParallel::setThreadOptions(3)'
==4601== Invalid read of size 8
==4601==    at 0xDDE360A: tbb::internal::generic_scheduler::allocate_task(unsigned long, tbb::task*, tbb::task_group_context*) (scheduler.cpp:320)
==4601==    by 0xDDE36FB: tbb::internal::generic_scheduler::generic_scheduler(tbb::internal::market&) (scheduler.cpp:100)
==4601==    by 0xDDE51EC: custom_scheduler (custom_scheduler.h:59)
==4601==    by 0xDDE51EC: tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::allocate_scheduler(tbb::internal::market&) (custom_scheduler.h:120)
==4601==    by 0xDDE3F55: allocate_scheduler (scheduler.cpp:42)
==4601==    by 0xDDE3F55: tbb::internal::generic_scheduler::create_master(tbb::internal::arena*) (scheduler.cpp:1161)
==4601==    by 0xDDDE9E9: tbb::internal::governor::init_scheduler(int, unsigned long, bool) (governor.cpp:200)
==4601==    by 0xDDDEB2E: tbb::task_scheduler_init::initialize(int, unsigned long) (governor.cpp:320)
==4601==    by 0xDD995D1: setThreadOptions (options.cpp:27)
==4601==    by 0x4943845: ??? (in /usr/lib64/R/lib/libR.so)
==4601==    by 0x4978C6F: ??? (in /usr/lib64/R/lib/libR.so)
==4601==    by 0x4995007: Rf_eval (in /usr/lib64/R/lib/libR.so)
==4601==    by 0x4996DF5: ??? (in /usr/lib64/R/lib/libR.so)
==4601==    by 0x4997B7A: Rf_applyClosure (in /usr/lib64/R/lib/libR.so)
==4601==  Address 0xfffffffffffffff7 is not stack'd, malloc'd or (recently) free'd
==4601== 

 *** caught segfault ***
address 0xfffffffffffffff7, cause 'memory not mapped'

Traceback:
 1: setTbbThreadOptions(numThreads, stackSize)
 2: RcppParallel::setThreadOptions(3)
```

This means that, on Fedora 32+, most RcppParallel-dependent packages cannot be even installed, because they usually call `setThreadOptions` several times in `.onLoad` (example: [`quanteda`](https://download.copr.fedorainfracloud.org/results/iucar/cran/fedora-32-x86_64/01301980-R-CRAN-quanteda/builder-live.log.gz)).

**Comment by kevinushey** [comment]
Agh. What a nightmare!

**Comment by kevinushey** [comment]
In the meantime, setting the environment variable:

```
RCPP_PARALLEL_BACKEND=tinythread
```

should work around the crash.

**Comment by Enchufa2** [comment]
> Agh. What a nightmare!

tbb or gcc10?

> In the meantime, setting the environment variable:
> 
> ```
> RCPP_PARALLEL_BACKEND=tinythread
> ```
> 
> should work around the crash.

Thanks!

**Comment by kevinushey** [comment]
> > Agh. What a nightmare!
> 
> tbb or gcc10?

Both :-)

More seriously, I've been trying to find a mechanism for packages to avoid using TBB on CRAN so that UBSAN errors don't get triggered, but this seems like a new issue.

> 
> > In the meantime, setting the environment variable:
> > ```
> > RCPP_PARALLEL_BACKEND=tinythread
> > ```
> > 
> > 
> > should work around the crash.
> 
> Thanks!

**Comment by kevinushey** [comment]
Looks like this is still an issue on the latest Rawhide. I think we'll eventually just have to switch over to using the system version of TBB on Linux.

**Comment by kevinushey** [comment]
Was just notified that this is an issue on other platforms with gcc 10.1 now, so I'm going to just disable attempts to change the scheduler after it's already been initialized once.

**Comment by Enchufa2** [comment]
I've seen the update. Now I'm building RcppParallel for Fedora with `RCPP_PARALLEL_BACKEND=tinythread` as suggested. Would you recommend to drop that now or to keep it until this is fixed?

**Comment by koheiw** [comment]
I noticed that we can call only `RcppParallel::setThreadOptions()` once in a session since v5.0.2. Our package, quanteda, sets `numThreads = 2` when loaded to avoid overuse of CPU on CRAN, but it makes it impossible for users to change the number. Can anyone suggest how to limit the number of threads in CRAN build and tests without affecting actual users?

**Comment by eddelbuettel** [comment]
I am a little fuzzy on the full details but I think I picked up somewhere that TBB in fact only lets you set this once. That was an issue for me in package [tiledb](https://cran.r-project.org/package=tiledb) which used to use TBB -- but for various reasons the underlying multithreaded logic was rewritten so the package no longer uses TBB by default.  I wish I had an actual reference --- right now I can only offer an 'at best' half-guided fear...

But in case [quanteda](https://cran.r-project.org/package=quanteda) wants to mimick what I set up:  a setup function respecting an option to set the default number of CPUs _before loading_ the package so that CRAN still gets two, and everybody else who wants more can get more.  Not claiming it is ideal, but I know that others ([data.table](https://cran.r-project.org/package=quanteda) comes to mind, with a very detailed discussion [here (linking to rendered man page)](https://www.rdocumentation.org/packages/data.table/versions/1.13.0/topics/setDTthreads)) do the same.   My code is below, the line setting TBB core is commented out as our default build no longer includes TBB.  

https://github.com/TileDB-Inc/TileDB-R/blob/1c38430cc82cfaa8b1e4d5b4998a933ef82c486a/R/Config.R#L215-L247

The functions is then called by the examples and tests, _e.g._ like this in the test files (and examples)

https://github.com/TileDB-Inc/TileDB-R/blob/1c38430cc82cfaa8b1e4d5b4998a933ef82c486a/inst/tinytest/test_arrayschema.R#L1-L6

**Comment by koheiw** [comment]
@eddelbuettel thank you. After reading you posts and links, this seems to be the best approach.
```r

get_threads <- function() {
    c("omp" = as.integer(Sys.getenv("OMP_THREAD_LIMIT")),
      "tbb" = as.integer(Sys.getenv("RCPP_PARALLEL_NUM_THREADS")),
      "max" = RcppParallel::defaultNumThreads())
}
unname(min(get_threads(), na.rm = TRUE))
```

**Comment by eddelbuettel** [comment]
That is nice.  One change I would make (as I suffering of OCB) is to make that `Sys.getenv()` with a fallback / alternate of `getOption(..., 2)` as the latter has this nice trick of giving a default value. So I sometimes nest `Sys.getenv()` and `getOption()` -- but it also all depends on how you roll with `quanteda` and I don't know what it does for its options.

**Comment by koheiw** [comment]
Thanks for the suggestion. I am hoping that `RcppParallel::defaultNumThreads()` returns a value always...

**Comment by kevinushey** [comment]
This will also be fixed in the next release of RcppParallel (we use per-task arenas, where we can control the thread count, rather than a global static scheduler configuration which bombs in gcc 10)

**Comment by kevinushey** [comment]
This should now (finally!) be fixed in the current release of RcppParallel (5.1.2).
