### ISSUE TITLE
Do we need -ltbb -ltbbmalloc on Linux and macOS?

### ISSUE THREAD

**Issue by krlmlr** [RcppCore/RcppParallel#129]
Without these, compilation fails in a package that uses `parallelReduce()` with a `Worker` . (Compilation works on Windows with the same package.) I haven't checked if work happens in parallel when I add these flags.

``` r
RcppParallel::RcppParallelLibs()
RcppParallel:::tbbLdFlags()
#> [1] ""
```

<sup>Created on 2020-08-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

## Example package

- Baseline: https://github.com/krlmlr/RcppParallelReprex
- Manually link TBB: Branch fix1
- Don't use TBB: Branch fix2

I was unable to whip up a reprex using `Rcpp::compileFunction()` .

## Error message

```sh
undefined symbol: _ZN3tbb4task13note_affinityEt
```

**Comment by kevinushey** [comment]
Can you share the compilation output you're seeing as well?

I think the problem here is that RcppParallel loads the requisite TBB libraries in its own `.onLoad()` handler here:

https://github.com/RcppCore/RcppParallel/blob/394a7295ea018a5863cbe76ccba86ff295e4a5f8/R/hooks.R#L5-L28

But because the package only links to RcppParallel, and doesn't import it (ie: it doesn't require RcppParallel to be loaded beforehand) then the TBB libraries don't get loaded and compilation fails.

The fix here would be to explicitly force the `RcppParallel` namespace to be loaded before loading the package.

**Comment by kevinushey** [comment]
A hacky way of doing this is to add:

```
Imports: RcppParallel
```

to the package DESCRIPTION, and

```
importFrom(RcppParallel, RcppParallelLibs)
```

to the NAMESPACE.

**Comment by kevinushey** [comment]
(this is basically the same hack as the `importFrom(Rcpp, evalCpp)`)

**Comment by krlmlr** [comment]
Thanks, confirmed.
