### ISSUE TITLE
RcppParallel 5.0.2 bug under Ubuntu 20.10 after debian install of r-cran-rcppparallel

### ISSUE THREAD

**Issue by harrelfe** [RcppCore/RcppParallel#135]
```
require(rstan)
stancode <- 'data {real y_mean;} parameters {real y;} model {y ~ normal(y_mean,1);}'
mod <- stan_model(model_code = stancode, verbose = TRUE)
```

Results in 

```
TRANSLATING MODEL '16a540c6086086816528e4524def24d9' FROM Stan CODE TO C++ CODE NOW.
successful in parsing the Stan model '16a540c6086086816528e4524def24d9'.
COMPILING THE C++ CODE FOR MODEL '16a540c6086086816528e4524def24d9' NOW.
OS: x86_64, linux-gnu; rstan: 2.21.2; Rcpp: 1.0.5; inline: 0.3.16 
Error in system.file("lib", .Platform$r_arch, package = "RcppParallel",  : 
  no file found
```
This example works fine with I install the package from source using `install.packages('RcppParallel')`.

**Comment by eddelbuettel** [comment]
Frank, that may be the wrong place for a follow-up from the r-sig-debian discussion.  You went upstream, and Kevin will likely tell you 'no bug' as you already said "works with `install.packages()`.  You probably want to talk to _downstream_ i.e. the Debian package maintainer.

**Comment by kevinushey** [comment]
This issue arises because of the patch used on Debian builds:

https://sources.debian.org/patches/r-cran-rcppparallel/5.0.2+dfsg-3/use_debian_packaged_libtbb.patch/

In particular, RcppParallel uses the system `tbb` library rather than the bundled version via this patch. However, `rstan` still assumes that `tbb` would be available via `RcppParallel`.

One simple way forward would be for `rstan` to allow for this path to be missing here.

**Comment by kevinushey** [comment]
This is a bug in `rstan` / `StanHeaders`. I filed a pull request here.

https://github.com/stan-dev/rstan/pull/930/files
