### ISSUE TITLE
System tbb autodetection

### ISSUE THREAD

**Issue by Enchufa2** [RcppCore/RcppParallel#163]
Would you be interested in this? I.e., a piece of code that detects tbb and sets `TBB_LIB` and `TBB_INC` automatically. If so,

- I can work on this (low priority, for a future release).
- What's the proper place for this? I'm willing to contribute the Unix version, and thus the most natural way for this would be shell code in the `configure` script.

**Comment by kevinushey** [comment]
I would definitely welcome that.

RcppParallel uses [configure](https://github.com/kevinushey/configure) for configuring (I wrote an R package for this because of how much I hate writing shell / autoconf scripts), so the right place to add this auto-configure code would be around here:

https://github.com/RcppCore/RcppParallel/blob/master/tools/config/configure.R

Note that this runs on both Windows + Unix by default, so you'd want to shield with `.Platform$OS.type` or something similar for unix-specific stuff.

**Comment by Enchufa2** [comment]
Perfect, I'll prepare a PR when I find some time.

**Comment by kevinushey** [comment]
Is this still something worth exploring?

**Comment by Enchufa2** [comment]
Yes, please keep this open. Apologies for the delay.
