### ISSUE TITLE
[Question] on forked processes

### ISSUE THREAD

**Issue by dipterix** [RcppCore/RcppParallel#171]
(This is not an issue. I'm not sure if I posted on a wrong place. Sorry if I did)

I was wondering how RcppParallel threads are set in forked processes. I know openmp has issues running with pthread, but I didn't see any issues for RcppParallel. 

Is there any concerns on whether threads should be set to one on forked processes?

Thanks

**Comment by kevinushey** [comment]
Sorry, but to be honest, I'm not sure. Since RcppParallel is effectively just an interface to Intel's TBB, I'd recommend reading their documentation to see if they mention anything specifically about how forks are handled, or designing some tests to confirm whether the behavior matches (or does not match) your expectations.

**Comment by dipterix** [comment]
Hmm, I thought when TBB is not supported, it uses non-intel tiny thread. 

The reason I was asking is because I haven't got any issues so far, but I'm quite worried if I could mess it up in the future. 

Thanks for answering my questions!
