### ISSUE TITLE
TBB version requirement?

### ISSUE THREAD

**Issue by MichaelChirico** [RcppCore/RcppParallel#177]
I don't see any version requirement listed in the DESCRIPTION:

https://github.com/RcppCore/RcppParallel/blob/659b32615b36de9f570ae319f56793a28013a3a2/DESCRIPTION#L32

Nor in the reference manual:

https://cran.r-project.org/web/packages/RcppParallel/RcppParallel.pdf

But on the `RcppParallel` website:

http://rcppcore.github.io/RcppParallel/

I see:

> Intel TBB (v4.3)

However, I don't see any such version over at the TBB repo:

https://github.com/oneapi-src/oneTBB/releases

The source copy in `src/tbb` seems to be "2018 update 8" which does match an upstream release. The oldest release in the repo is "Intel(R) Threading Building Blocks 4.4" -- is "4.3" supposed to mean "no known version requirement", then?

**Comment by kevinushey** [comment]
This is mainly because RcppParallel in the past has only been built against the bundled version of TBB, but in theory I think you could use RcppParallel with most versions of TBB (as they've been pretty good about maintaining API / ABI compatibility).

In general though, unless you're using the bundled version of TBB, the onus is on the user to verify that things function as expected.

**Comment by MichaelChirico** [comment]
thanks. should we remove the "4.3" reference on the website? that seems to go against this advice a bit

**Comment by kevinushey** [comment]
Thanks; I've made that change. FWIW, documentation on using RcppParallel together with a custom version of TBB is currently within the README file: https://github.com/RcppCore/RcppParallel/blob/master/README.md
