### ISSUE TITLE
[Question] C++11 not supported by CRAN

### ISSUE THREAD

**Issue by Jean-Romain** [RcppCore/RcppParallel#44]
Hi,

I'm interesting by RcppParallel. I read on the [doc](https://rcppcore.github.io/RcppParallel/index.html#r_packages) that RcppParallel compiles in C++11 (`CXX_STD = CXX11`)

I submitted a package to the CRAN which was written for C++11 . It was accepted by the CRAN but the compilation failed on Windows platform because - I quote prof Brian Ripley - *full C++11 is not available on gcc 4.6 used on r-oldrelease-windows*. So I rewrote some parts of the code to be ISO C++98.

So I'm struggled with the following question: can we really use RcppParallel in a package?

Thanks

**Comment by kevinushey** [comment]
My recommendation would be to tell the CRAN team that you don't intend for your package to be used with R-oldrel, and lack the resources to conform to the C++11 subset supported by R-oldrel.

A number of packages do successfully use RcppParallel on CRAN (see e.g. the reverse depends on https://cran.r-project.org/web/packages/RcppParallel/index.html) so whatever failure is occurring is likely due to C++11 code you're using that's independent on RcppParallel.

**Comment by eddelbuettel** [comment]
As per a grep I ran recently there are over 120 packages _on CRAN_ which specify C++11.  It has been allowed since R 3.1.0 -- almost three years ago.  See [this very recent post](http://gallery.rcpp.org/articles/rcpp-and-c++11-c++14-c++17/) for more.

`g++-4.6.*` is "good enough" for some things, but not others.  You could test against it and fail.

We do have packages on CRAN requiring _full C++11_ (ie RcppArmadillo) and even one (per the documentation in the _R-devel version of Writing R Extensions_) requiring C++14.

So I think you overreacted. You do not have to port back to C++98.  Just document that you use C++11 in SystemRequirements and then `src/Makevars{,.win}`.

**Comment by Jean-Romain** [comment]
Thank you for your anwsers. It's almost the answer I was expecting. 

I found that it is very difficult to find answers to such technical questions. Moreover it is at the edge of my knowledge in programming so it is even harder to me. That is why I rewrote some parts in C++98 because it was easy and it concerned only few lines of code. Doing so I ensured to do no get any additional problem.

The post about Rcpp and C++11-14-17 is very informative thank you.

**Comment by eddelbuettel** [comment]
Yes, it can be tricky.  Not that long ago the [r-package-devel](https://stat.ethz.ch/mailman/listinfo/r-package-devel) list was set up, it continues to be a very good resources I can wholeheartedly recommend next time you have a question.
